#!/bin/bash

fnHelp () {
    echo "runserve help            - show help!!!"
    echo "         init            - initialize runserver config"
    echo "         version         - version of this file"
    echo "         update          - updating this file"
    echo "         stop            - stopping container"
    echo "         nodaemon        - run container with no daemon"
    exit 1
}

fnVersion () {
  latest=$(curl -s https://raw.githubusercontent.com/runserve/runserve/master/runserve.latest)
    sleep 2
    echo $latest
    echo "v0.1"
    echo $latest
    exit 1
}

fnBash () {
    fnGetConfig
    docker run --rm --name=$containerName-$port -it -v $(pwd):/app -e GITUSER="$gitUser" -e GITEMAIL="$gitEmail" -e PORT=$port -p $port:$port -p 8080:8080 $dockerImage containerStart $2 $3 $4 $5 $6 $7 $8 $9
    #read -p "Commit changes before terminate runserver? [Y/n]: " changes
    exit 1
}

fnGetConfig () {
    source .runserve/config
    if [ ${#containerName} -lt '2' ]; then
      fnInitConfig
    else
      source .runserve/config
    fi
}

fnInitConfig () {
    ### CHECK CONFIG VARS:
    mkdir .runserve
    touch ./.runserve/config
        read -p 'Choose Angular local port (4200-4219)[4200]: ' port
        if [ ${#port} -lt 3 ]; then
            echo "port='4200'" > $LOCAL_CONFIG
            port=4200
        else
            echo "port='$port'" >> $LOCAL_CONFIG
        fi
        read -p 'Github login: ' gitUser
        if [ ${#gitUser} -gt 3 ]; then
            echo "gitUser='$gitUser'" >> $LOCAL_CONFIG
        fi
        read -p 'Github email: ' gitEmail
        if [ ${#gitEmail} -gt 3 ]; then
            echo "gitEmail='$gitEmail'" >> $LOCAL_CONFIG
        fi
        echo "Choose RUNSERVE version:"
            echo "1) Angular 7.3.1"
            echo "2) Angular 7.3.2"
            echo "3) Angular 7.3.3"
            read -p "Choose: " dockerImage
            if [[ $dockerImage = 1 || $docker_image = 7.3.1 ]]; then
                dockerImage="runserve/angular_7.3.1:0.1"
                echo $dockerImage
            elif [[ $dockerImage = 2 || $docker_image = 7.3.2 ]]; then
                dockerImage="runserve/angular_7.3.2:0.1"
                echo $dockerImage
            elif [[ $dockerImage = 3 || $dockerImage = 7.3.3 ]]; then
                dockerImage="runserve/angular_7.3.3:0.1"
                echo $dockerImage
            fi
            echo "dockerImage='$dockerImage'" >> $LOCAL_CONFIG
        read -p "Default container name [angular-dev-env-"$port"]: " containerName
        if [ ${#containerName} -lt 3 ]; then
            echo "containerName='angular-dev-env'" >> $LOCAL_CONFIG
        else
            echo "containerName='$containerName'" >> $LOCAL_CONFIG
        fi
    if [[ $1 = bash ]]; then fnBash
    else
      exit 1;
    fi
}







#################################################################
### OS DETECT:
# if [[ "$OSTYPE" == "linux-gnu" ]]; then
#         RAND=$(shuf -i 100-199 -n 1)
# elif [[ "$OSTYPE" == "darwin"* ]]; then
#         RAND=$(jot -r 1 100 199)
# fi
#################################################################
### READ CONFIG VARS:


#GLOBAL_CONFIG=~/.config/runserve/runserve.config
LOCAL_CONFIG=./.runserve/config
#source $GLOBAL_CONFIG
if [ -f $LOCAL_CONFIG ]; then
    source $LOCAL_CONFIG
else
  fnInitConfig
fi
################################################################

#################################################################
## CTRL-V CTRL-Z KEYPRESS:
stty quit "^Z"
trap " docker stop $containerName" 3;
trap ctrl_c INT
function ctrl_c(){
    read -p "Commit changes before terminate runserver?" changes
    echo " docker stopping, wait few seconds..."
    docker stop $containerName
    echo 'docker stopped'
}
#################################################################


if [[ $1 = version ]]; then fnVersion
elif [[ $1 = init ]]; then fnInitConfig
elif [[ $1 = -h || $1 = --help || $1 = help ]]; then fnHelp
elif [[ $1 = bash ]]; then fnBash
elif [[ $1 = update ]]; then
    if [[ $2 = dev ]]; then
        if [[ $3 = getfrombin ]]; then
            cp ~/bin/runserve ./runserve
        elif [[ $3 = puttobin ]]; then
            cp ./runserve ~/bin/runserve
        else
            echo 'getfrombin || puttobin'
        fi
    else
    echo 'comming soon...'
    fi
    exit 1
else fnHelp

fi
